# Generated by Django 4.0.6 on 2023-06-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cad_usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
